title: Naser Mirzaei
description: My Personal Web Page, I Will Write Everything Here
url: 'https://nasermirzaei89.net'
baseurl: ''

author: Naser Mirzaei

github:
  username: nasermirzaei89

linkedin:
  username: nasermirzaei89

instagram:
  username: nasermirzaei89

telegram:
  username: nasermirzaei89

permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      type: 'posts'
      layout: 'post'

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

feed:
  path: /feed.xml

disqus:
  shortname: nasermirzaei89-net

webmaster_verifications:
  google: 'N0-Uhbzok_3jUy0rzsYLnwy31QR9oho9zXQzcOpPQ2s'
  bing: '5CB9E0C8772EAD71543DB4009B38FF57'
  yandex: '7a25c3fb2fa9c6b1'
#  alexa: 1234
